# Generated by Django 2.2.5 on 2019-09-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='publication',
            field=models.CharField(max_length=200),
        ),
    ]
